version: '3.1'
services:
  db:
    image: postgres:14.3-alpine
    command: ["postgres", "-c", "log_statement=all"]
    container_name: postgres
    ports:
      - ${PORT_DB_OUT}:${PORT_DB}
    volumes:
      - ${PATH_TO_DB_OUT}:${PG_DATE}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PG_DATE: ${PG_DATE}
    restart: always
