version: '3.1'
services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - ${PORT_OUT}:5432
    volumes:
      - ${PATH_TO_DB_OUT}:${PG_DATE}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATE: ${PG_DATE}
    restart: always
