version: '3.1'
services:

  fastapi:
    container_name: E-card-eyes-server
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    command:  python -m binocular_vision
    restart: always
    
  db:
    image: postgres:14.3-alpine
    command: ["postgres", "-c", "log_statement=all"]
    container_name: postgres
    ports:
      - ${PORT_DB_OUT}:${PORT_DB}
    volumes:
      - ${PATH_TO_DB_OUT}:${PG_DATE}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PG_DATE: ${PG_DATE}
    restart: always

  # db-test:
  #  image: postgres:14.3-alpine
  #  command: ["postgres", "-c", "log_statement=all"]
  #  container_name: postgres-test
  #  ports:
  #    - ${PORT_DB_OUT_TEST}:${PORT_DB}
  #  environment:
  #    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #    POSTGRES_USER: ${POSTGRES_USER}
  #    POSTGRES_DB: ${POSTGRES_DB_NAME_TEST}
  #    PG_DATE: ${PG_DATE}
  #    restart: always